default_install_hook_types:
  - pre-commit
  - pre-merge-commit
  - commit-msg
default_stages:
  - pre-commit
  - pre-merge-commit
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-vcs-permalinks
        name: check that VCS links are permanent links
      - id: detect-private-key
        name: check for added private keys
      - id: mixed-line-ending
        name: check for mixed line endings
        args: [--fix=no]
      - id: trailing-whitespace
      - id: check-toml
        name: check TOML is parsable
      - id: check-yaml
        name: check YAML is parsable
  - repo: local
    hooks:
      - id: gitlint
        name: check commit message is in conventional commits format
        entry: gitlint
        language: system
        args: [--staged, --msg-filename]
        stages: [commit-msg]
      - id: mdformat
        name: format with mdformat
        entry: mdformat
        language: system
        args: [--check]
        types: [markdown]
      - id: nixfmt
        name: format with nixfmt
        entry: nixfmt
        language: system
        args: [--verify]
        types: [nix]
      - id: stylua
        name: format with stylua
        entry: stylua
        language: system
        args: [--search-parent-directories]
        types: [lua]
        exclude: '^.config/nvim/lua/config/mappings\.lua$'
      - id: yamlfmt
        name: format with yamlfmt
        entry: yamlfmt
        language: system
        types: [yaml]
        exclude: '^.config/gh/config.yaml$'
